name: Container Build
description: コンテナイメージをビルドし、ECRへプッシュします。
inputs:
  ecr-repository-uri:
    required: true
    description: ECRリポジトリのURI
  dockerfile-path:
    required: true
    description: Dockerfileのパス
outputs:
  container-image:
    value: ${{ steps.meta.outputs.tags }}
    description: ビルドしたコンテナイメージ
runs:
  using: composite
  steps:
    - name: デバッグ情報の出力
      run: |
        echo "ECRリポジトリURI: ${{ inputs.ecr-repository-uri }}"
        echo "Dockerfileのパス: ${{ inputs.dockerfile-path }}"
        aws sts get-caller-identity
      shell: bash
    - uses: aws-actions/amazon-ecr-login@v2
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: ${{ inputs.ecr-repository-uri }}
        tags: type=sha, format=long
    - uses: docker/build-push-action@v6
      with:
        push: true
        context: ${{ inputs.dockerfile-path }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
